# EPSY 5122: Programming for Social Science Researchers
## Assignment 11
### Due Tuesday, November 29, 2022 by 2:30pm

#### Problem 0

If you've made it to this document, you likely already did Problem 0 from the readme.  But just in case, here it is again!

a) Let's watch some videos! I recommend all the videos in this series (for future learning), but we will just focus on two now. Watch the first half of this video (https://www.youtube.com/watch?v=_NrSWLQsDL4&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV&index=3) -- just the part about forking, you can ignore pull requests!  Then watch this video:
https://www.youtube.com/watch?v=yXT1ElMEkW8&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV&index=6 (you don't have to do the terminal git commands, you can use the GitKraken clone strategy we used in class)

b) Using what you learned in 0a, **fork** my GitHub repository (remote repo) to your own account, then **clone** to your hard drive (local repo) using GitKraken (or use the command-line if you want the extra challenge).  After finishing EACH problem below, make sure to STAGE and COMMIT with a comment (e.g., "Just finished Part 1! Git is fun!" or whatever).  Then PUSH back to GitHub.

###### Note on privacy!

By default, GitHub repos are public (promoting open source sharing of code), but of course you are more than welcome to make your code for this assignment private, as is your right!  Unfortunately, it's a little bit complicated because GitKraken recently made a change that the free version of their software doesn't allow for private repo access, and you need the paid version.  So here are 3 ways to do this privately:

1) GitKraken partners with GitHub to provide a free pack of resources (including the pro version of GitKraken) for *students*.  That's you!  So you can sign up here *only if you want to do this*: https://education.github.com/pack?utm_source=github+gitkraken

2) Just keep your GitHub repo public while you're working on this project.  Use free GitKraken.  Then switch the GitHub repo to Private only when you're done using GitKraken to push to GitHub.

3) Keep the repo private and use the terminal git commands in the YouTube video for Problem 0a.

To make the repo private:
On your GitHub repo, go to Settings > Manage Access > Manage (under Public Repository) > Change Visibility.  Then add me (jkbye) as a 'collaborator' so I can see it: Settings > Manage Access > Invite a Collaborator (green button) > add 'jkbye'.

#### Problem 1

Now let's get to Jupyter!

a) Import any helpful libraries in this Jupyter Notebook.

b) Load the *MA_Public_Schools_2017.csv* file as a pandas data frame.  Note: these data are from Kaggle: https://www.kaggle.com/ndalziel/massachusetts-public-schools-data and I have already removed a lot of columns.

c) Adapt the example code in the chunk below to replace all spaces in column names with underscores. This is good practice in order to not cause problems with functions that don't allow spaces in variable names (e.g., **smf.ols**).

d) Adapt the code from 1c to replace "%" sign with "Perc", because it is also good practice not to start column names with symbols.

e) Find the descriptives for numeric columns.

f) Commit your changes and push to GitHub!

In [45]:
# Problem 1 code here (can split into multiple code chunks if you want)
import os
os.chdir('C:\\Users\\kayle\\Documents\\PFUND\\f22_pfssr_assignment11\\in_data')
import pandas as pd
school_data = pd.read_csv("MA_Public_Schools_2017.csv")

# starter code for 1c -- replace school_data w/ your dataframe name
school_data.columns = school_data.columns.str.replace(' ', '_') # notice this replaces the 1st argument w/ the 2nd

# 1d
school_data.columns = school_data.columns.str.replace('%', 'Perc') # notice this replaces the 1st argument w/ the 2nd

#1e
school_data.describe()

,School_Code,District_Code,PK_Enrollment,K_Enrollment,1_Enrollment,2_Enrollment,3_Enrollment,4_Enrollment,5_Enrollment,6_Enrollment,...,Number_of_Students,Salary_Totals,Average_Salary,FTE_Count,In-District_Expenditures,Total_In-district_FTEs,Average_In-District_Expenditures_per_Pupil,Total_Expenditures,Total_Pupil_FTEs,Average_Expenditures_per_Pupil
count,1.861000e+03,1.861000e+03,1861.000000,1861.000000,1861.000000,1861.000000,1861.000000,1861.000000,1861.000000,1861.000000,...,1823.000000,1.769000e+03,1769.000000,1769.000000,1.768000e+03,1768.000000,1768.00000,1.768000e+03,1768.000000,1768.000000
mean,2.918442e+06,2.918254e+06,15.837722,35.535196,36.629232,37.518538,38.584632,38.717356,38.089199,37.879635,...,523.515634,5.625178e+07,74036.641040,707.853024,1.518097e+08,9376.335633,14573.85582,1.731198e+08,10466.072624,15038.254949
std,3.941407e+06,3.941370e+06,37.784512,44.632989,42.732414,43.842672,46.541783,48.915559,55.040382,75.304290,...,357.861705,9.335788e+07,7990.377315,1065.807405,2.661339e+08,14015.732845,2940.80342,3.093057e+08,16287.467986,2743.977057
min,1.000200e+04,1.000000e+04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.000000,5.534000e+04,34588.000000,2.000000,6.975500e+05,38.400000,9451.51000,1.132413e+06,82.800000,10399.970000
25%,9.700600e+05,9.700000e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,306.500000,1.215839e+07,68572.000000,166.000000,3.061598e+07,2312.150000,12785.25000,3.353242e+07,2442.900000,13339.700000
50%,2.100410e+06,2.100000e+06,0.000000,17.000000,22.000000,20.000000,16.000000,16.000000,0.000000,0.000000,...,445.000000,2.269741e+07,73471.000000,308.000000,5.293331e+07,4205.300000,13599.49000,5.863741e+07,4392.000000,14137.480000
75%,3.310030e+06,3.310000e+06,15.000000,64.000000,66.000000,68.000000,71.000000,70.000000,66.000000,45.000000,...,634.500000,4.808571e+07,78256.000000,627.000000,1.287478e+08,7700.400000,15478.08000,1.335444e+08,8378.900000,15900.290000
max,3.902090e+07,3.902000e+07,560.000000,557.000000,245.000000,250.000000,319.000000,446.000000,487.000000,490.000000,...,4327.000000,3.838662e+08,100731.000000,4323.000000,1.093104e+09,56858.800000,38780.85000,1.269580e+09,65964.600000,30505.050000

#### Problem 2

a) Remove the District Code column.

b) Create a new column called "TOTAL_Enrollment" that is the sum of all columns that end in "Enrollment".

c) Compute the mean of "TOTAL_Enrollment" for each District. (Hint: groupby)

d) Commit your changes and push to GitHub!

In [46]:
# Problem 2 code here (can split into multiple code chunks if you want)
# a)
school_data = school_data.drop(columns="District_Code")
# b)
school_data['TOTAL_Enrollment'] = school_data.loc[:,school_data.columns.str.contains("Enrollment")].sum(axis=1)
#c)
school_data.groupby('District_Name')["TOTAL_Enrollment"].mean()

District_Name
Abby Kelley Foster Charter Public (District)            1425.000000
Abington                                                 383.200000
Academy Of the Pacific Rim Charter Public (District)     527.000000
Acton-Boxborough                                         620.888889
Acushnet                                                 477.500000
                                                           ...
Winthrop                                                 492.750000
Woburn                                                   420.727273
Worcester                                                566.200000
Worthington                                               60.000000
Wrentham                                                 515.500000
Name: TOTAL_Enrollment, Length: 410, dtype: float64

#### Problem 3

a) Visualize each bivariate relationship among Average_Class_Size, Average_Salary, Perc_Economically_Disadvantaged, and Perc_English_Language_Learner.  Use the Seaborn function **pairplot**.  The argument to `pairplot` should be `school_data[['Average_Class_Size', 'Average_Salary', 'Perc_Economically_Disadvantaged', 'Perc_English_Language_Learner']]`, which will just pull those columns out from the full data frame.

b) Describe what you see from the plots.

c) Based on your observations from 3b, and as a completely post-hoc, exploratory analysis, choose one of the 4 measures from 3a to be an outcome variable, and a second measure to be a predictor variable.  Then run a linear regression, print the *summary*, and write a sentence interpreting the results (does not need to be detailed, just practice retrieving the relevant info on predictor significance, etc.)

d) Commit your changes and push to GitHub!

In [47]:
# Problem 3 code here (can split into multiple code chunks if you want)
import seaborn as sns
import numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf

# a)
sns.pairplot(school_data[['Average_Class_Size', 'Average_Salary', 'Perc_Economically_Disadvantaged', 'Perc_English_Language_Learner']])
# b)
#Percent ELL seems positively correlated with Percent economically disadvantaged, average salary, and average class size, but average class size and salary don't seem to be correlated with each other.
# c)
school_reg = smf.ols('Average_Class_Size ~ Perc_English_Language_Learner', data=school_data).fit()
print(school_reg.summary())
#For every increase in 1 percent english language learners, the predicted average class size increases by 0.03 people on average; the p value is less than 0.01, indicating this is a significant relationship.

                            OLS Regression Results
==============================================================================
Dep. Variable:     Average_Class_Size   R-squared:                       0.010
Model:                            OLS   Adj. R-squared:                  0.010
Method:                 Least Squares   F-statistic:                     18.48
Date:                Fri, 25 Nov 2022   Prob (F-statistic):           1.81e-05
Time:                        00:16:37   Log-Likelihood:                -5089.1
No. Observations:                1823   AIC:                         1.018e+04
Df Residuals:                    1821   BIC:                         1.019e+04
Df Model:                           1
Covariance Type:            nonrobust
=================================================================================================
                                    coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
Intercept                        18.0324      0.114    157.888      0.000      17.808      18.256
Perc_English_Language_Learner     0.0301      0.007      4.298      0.000       0.016       0.044
==============================================================================
Omnibus:                      163.102   Durbin-Watson:                   1.767
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              535.372
Skew:                          -0.425   Prob(JB):                    5.56e-117
Kurtosis:                       5.515   Cond. No.                         20.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

#### Problem 4

a) Create a new linear regression model that takes the model from 3c and adds both of the remaining variables from 3a as additional predictor variables.  To do this, the formula interface would look like `"outcome_name ~ predictor1_name + predictor2_name + predictor3_name"`

b) Print the summary from 4a, and write a short interpretation of the results, especially comparing it to Problem 3c.  

c) Add School_Type as another predictor to your model.  Interpret the new predictor in your output.  How is it different from the other predictors?

d) Commit your changes and push to GitHub!

In [4]:
# Problem 4 code here (can split into multiple code chunks if you want)
# a)
school_reg4 = smf.ols('Average_Class_Size ~ Perc_English_Language_Learner + Perc_Economically_Disadvantaged + Average_Salary', data=school_data).fit()
# b)
print(school_reg4.summary())
#In this model, Percent ELL and Percent economically disadvantaged are both significant predictors for average class size, but average salary is not. 
# The coefficient also increased from 0.03 to 0.08, indicating that an increase in percent ELL is associated with a *greater* predicted increase in average class size when accounting for percent economically disadvantaged and average salary.
# c)
school_regc = smf.ols('Average_Class_Size ~ Perc_English_Language_Learner + Perc_Economically_Disadvantaged + Average_Salary + School_Type', data=school_data).fit()
print(school_regc.summary())
# School Type is a categorical variable, as compared to the other variables which are numeric/continuous.
# As compared to private schools, the predicted average class size for public schools will have 9.8 more people (holding all other variables constant).

                            OLS Regression Results
==============================================================================
Dep. Variable:     Average_Class_Size   R-squared:                       0.063
Model:                            OLS   Adj. R-squared:                  0.061
Method:                 Least Squares   F-statistic:                     38.75
Date:                Tue, 29 Nov 2022   Prob (F-statistic):           3.08e-24
Time:                        10:40:04   Log-Likelihood:                -4768.1
No. Observations:                1743   AIC:                             9544.
Df Residuals:                    1739   BIC:                             9566.
Df Model:                           3
Covariance Type:            nonrobust
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
Intercept                          19.6251      0.957     20.518      0.000      17.749      21.501
Perc_English_Language_Learner       0.0825      0.010      8.587      0.000       0.064       0.101
Perc_Economically_Disadvantaged    -0.0518      0.005     -9.590      0.000      -0.062      -0.041
Average_Salary                  -7.414e-06   1.25e-05     -0.594      0.552   -3.19e-05    1.71e-05
==============================================================================
Omnibus:                      104.914   Durbin-Watson:                   1.783
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              262.181
Skew:                          -0.336   Prob(JB):                     1.17e-57
Kurtosis:                       4.777   Cond. No.                     7.97e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.97e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
                            OLS Regression Results
==============================================================================
Dep. Variable:     Average_Class_Size   R-squared:                       0.063
Model:                            OLS   Adj. R-squared:                  0.061
Method:                 Least Squares   F-statistic:                     38.75
Date:                Tue, 29 Nov 2022   Prob (F-statistic):           3.08e-24
Time:                        10:40:04   Log-Likelihood:                -4768.1
No. Observations:                1743   AIC:                             9544.
Df Residuals:                    1739   BIC:                             9566.
Df Model:                           3
Covariance Type:            nonrobust
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
Intercept                           9.8126      0.478     20.518      0.000       8.875      10.751
School_Type[T.Public School]        9.8126      0.478     20.518      0.000       8.875      10.751
Perc_English_Language_Learner       0.0825      0.010      8.587      0.000       0.064       0.101
Perc_Economically_Disadvantaged    -0.0518      0.005     -9.590      0.000      -0.062      -0.041
Average_Salary                  -7.414e-06   1.25e-05     -0.594      0.552   -3.19e-05    1.71e-05
==============================================================================
Omnibus:                      104.914   Durbin-Watson:                   1.783
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              262.181
Skew:                          -0.336   Prob(JB):                     1.17e-57
Kurtosis:                       4.777   Cond. No.                     4.83e+20
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.14e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

#### Problem 5

a) Save this Jupyter notebook as an HTML file (File > Download As > HTML) into your local repository (this folder). By default, Jupyter may put your HTML file in your default Downloads folder (wherever that is) -- if that happens, just manually move the file into this repo folder.

b) Stage, commit, and push all changes to your GitHub repository.

c) Submit a link to your repository as your submission for the assignment on Canvas. Remember the note from Problem 0: you can keep your repo private and add me as a collaborator.